// SYNTHETIC DEMO DATA ONLY. All names, complaints, and details are
// fictional. No real citizens, phone numbers, emails, or IDs are used.

const daysAgo = (n) => new Date(Date.now() - n * 24 * 60 * 60 * 1000);

const citizenRequests = [
  // ---- Ranchi (JH) — heavy healthcare + roads complaints ----
  { requestId: 'REQ-0001', originalText: 'हमारे मोहल्ले में सरकारी अस्पताल में डॉक्टर बहुत कम आते हैं।', language: 'hi', translatedText: 'Doctors rarely visit the government hospital in our neighborhood.', category: 'Healthcare', subCategory: 'Doctor availability', problem: 'Insufficient doctor availability at local hospital', location: { country: 'India', state: 'Jharkhand', district: 'Ranchi' }, latitude: 23.351, longitude: 85.312, locationConfidence: 'HIGH', urgency: 'HIGH', confidence: 88, source: 'text', timestamp: daysAgo(4) },
  { requestId: 'REQ-0002', originalText: 'The nearest government hospital is more than 20 km away from our village.', language: 'en', translatedText: 'The nearest government hospital is more than 20 km away from our village.', category: 'Healthcare', subCategory: 'Facility distance', problem: 'Long distance to nearest healthcare facility', location: { country: 'India', state: 'Jharkhand', district: 'Ranchi' }, latitude: 23.298, longitude: 85.334, locationConfidence: 'HIGH', urgency: 'HIGH', confidence: 91, source: 'voice', timestamp: daysAgo(9) },
  { requestId: 'REQ-0003', originalText: 'अस्पताल में दवाइयों की भारी कमी है।', language: 'hi', translatedText: 'There is a severe shortage of medicines at the hospital.', category: 'Healthcare', subCategory: 'Medicine shortage', problem: 'Medicine shortage at primary health center', location: { country: 'India', state: 'Jharkhand', district: 'Ranchi' }, latitude: 23.362, longitude: 85.289, locationConfidence: 'MEDIUM', urgency: 'MEDIUM', confidence: 74, source: 'messaging', timestamp: daysAgo(15) },
  { requestId: 'REQ-0004', originalText: 'गांव में एम्बुलेंस सेवा उपलब्ध नहीं है, मरीजों को ले जाने में बहुत परेशानी होती है।', language: 'hi', translatedText: 'No ambulance service is available in the village, causing major difficulty transporting patients.', category: 'Healthcare', subCategory: 'Emergency transport', problem: 'No ambulance service available', location: { country: 'India', state: 'Jharkhand', district: 'Ranchi' }, latitude: 23.319, longitude: 85.301, locationConfidence: 'HIGH', urgency: 'HIGH', confidence: 90, source: 'voice', timestamp: daysAgo(2) },
  { requestId: 'REQ-0005', originalText: 'The primary health center has only one nurse for the entire ward.', language: 'en', translatedText: 'The primary health center has only one nurse for the entire ward.', category: 'Healthcare', subCategory: 'Staff shortage', problem: 'Understaffed primary health center', location: { country: 'India', state: 'Jharkhand', district: 'Ranchi' }, latitude: 23.34, longitude: 85.327, locationConfidence: 'MEDIUM', urgency: 'MEDIUM', confidence: 70, source: 'text', timestamp: daysAgo(20) },
  { requestId: 'REQ-0006', originalText: 'बच्चों के टीकाकरण के लिए स्वास्थ्य केंद्र बहुत दूर है।', language: 'hi', translatedText: 'The health center for child vaccinations is very far away.', category: 'Healthcare', subCategory: 'Immunization access', problem: 'Poor access to child immunization services', location: { country: 'India', state: 'Jharkhand', district: 'Ranchi' }, latitude: 23.309, longitude: 85.35, locationConfidence: 'HIGH', urgency: 'HIGH', confidence: 85, source: 'text', timestamp: daysAgo(6) },
  { requestId: 'REQ-0007', originalText: 'The main road connecting our village to the highway has huge craters after the monsoon.', language: 'en', translatedText: 'The main road connecting our village to the highway has huge craters after the monsoon.', category: 'Roads & Transport', subCategory: 'Road damage', problem: 'Severe road damage after monsoon', location: { country: 'India', state: 'Jharkhand', district: 'Ranchi' }, latitude: 23.372, longitude: 85.295, locationConfidence: 'HIGH', urgency: 'MEDIUM', confidence: 80, source: 'text', timestamp: daysAgo(11) },
  { requestId: 'REQ-0008', originalText: 'सड़क पर स्ट्रीट लाइट न होने से रात में आना-जाना खतरनाक है।', language: 'hi', translatedText: 'Lack of street lights makes travel dangerous at night.', category: 'Roads & Transport', subCategory: 'Street lighting', problem: 'No street lighting on main road', location: { country: 'India', state: 'Jharkhand', district: 'Ranchi' }, latitude: 23.33, longitude: 85.31, locationConfidence: 'MEDIUM', urgency: 'LOW', confidence: 65, source: 'messaging', timestamp: daysAgo(25) },

  // ---- Jamshedpur (JH) — good infra, low complaint volume ----
  { requestId: 'REQ-0009', originalText: 'Minor pothole near the market road, not urgent but should be noted.', language: 'en', translatedText: 'Minor pothole near the market road, not urgent but should be noted.', category: 'Roads & Transport', subCategory: 'Minor road damage', problem: 'Small pothole near market area', location: { country: 'India', state: 'Jharkhand', district: 'Jamshedpur' }, latitude: 22.81, longitude: 86.198, locationConfidence: 'HIGH', urgency: 'LOW', confidence: 60, source: 'text', timestamp: daysAgo(30) },
  { requestId: 'REQ-0010', originalText: 'Our school library could use more updated reference books.', language: 'en', translatedText: 'Our school library could use more updated reference books.', category: 'Education', subCategory: 'Library resources', problem: 'Outdated library resources at government school', location: { country: 'India', state: 'Jharkhand', district: 'Jamshedpur' }, latitude: 22.795, longitude: 86.21, locationConfidence: 'MEDIUM', urgency: 'LOW', confidence: 55, source: 'text', timestamp: daysAgo(35) },
  { requestId: 'REQ-0011', originalText: 'Internet speed at the community center drops significantly during peak hours.', language: 'en', translatedText: 'Internet speed at the community center drops significantly during peak hours.', category: 'Internet & Digital Connectivity', subCategory: 'Bandwidth issue', problem: 'Slow internet during peak hours at community center', location: { country: 'India', state: 'Jharkhand', district: 'Jamshedpur' }, latitude: 22.8, longitude: 86.19, locationConfidence: 'HIGH', urgency: 'MEDIUM', confidence: 68, source: 'messaging', timestamp: daysAgo(18) },

  // ---- Dhanbad (JH) ----
  { requestId: 'REQ-0012', originalText: 'अस्पताल में एक्स-रे मशीन कई महीनों से खराब पड़ी है।', language: 'hi', translatedText: 'The X-ray machine at the hospital has been broken for several months.', category: 'Healthcare', subCategory: 'Equipment failure', problem: 'X-ray machine non-functional for months', location: { country: 'India', state: 'Jharkhand', district: 'Dhanbad' }, latitude: 23.8, longitude: 86.43, locationConfidence: 'HIGH', urgency: 'MEDIUM', confidence: 78, source: 'text', timestamp: daysAgo(14) },
  { requestId: 'REQ-0013', originalText: 'Frequent power cuts in our locality lasting 4-5 hours daily.', language: 'en', translatedText: 'Frequent power cuts in our locality lasting 4-5 hours daily.', category: 'Electricity', subCategory: 'Power outages', problem: 'Frequent long power outages', location: { country: 'India', state: 'Jharkhand', district: 'Dhanbad' }, latitude: 23.79, longitude: 86.44, locationConfidence: 'HIGH', urgency: 'MEDIUM', confidence: 82, source: 'text', timestamp: daysAgo(8) },
  { requestId: 'REQ-0014', originalText: 'खदान क्षेत्र के पास सड़क धंस गई है, वाहन चलाना खतरनाक है।', language: 'hi', translatedText: 'The road near the mining area has collapsed, making it dangerous to drive.', category: 'Roads & Transport', subCategory: 'Road collapse', problem: 'Road subsidence near mining area', location: { country: 'India', state: 'Jharkhand', district: 'Dhanbad' }, latitude: 23.805, longitude: 86.42, locationConfidence: 'HIGH', urgency: 'HIGH', confidence: 89, source: 'voice', timestamp: daysAgo(3) },
  { requestId: 'REQ-0015', originalText: 'Waiting time at the local clinic is quite long but manageable.', language: 'en', translatedText: 'Waiting time at the local clinic is quite long but manageable.', category: 'Healthcare', subCategory: 'Wait times', problem: 'Long wait times at local clinic', location: { country: 'India', state: 'Jharkhand', district: 'Dhanbad' }, latitude: 23.785, longitude: 86.45, locationConfidence: 'MEDIUM', urgency: 'LOW', confidence: 58, source: 'text', timestamp: daysAgo(28) },
  { requestId: 'REQ-0016', originalText: 'ट्रांसफार्मर खराब होने से पूरे मोहल्ले की बिजली गायब है।', language: 'hi', translatedText: 'A broken transformer has left the entire neighborhood without electricity.', category: 'Electricity', subCategory: 'Transformer failure', problem: 'Transformer failure causing area-wide outage', location: { country: 'India', state: 'Jharkhand', district: 'Dhanbad' }, latitude: 23.81, longitude: 86.41, locationConfidence: 'HIGH', urgency: 'MEDIUM', confidence: 80, source: 'messaging', timestamp: daysAgo(6) },

  // ---- Gaya (BR) — poor healthcare & water, high urgency ----
  { requestId: 'REQ-0017', originalText: 'सरकारी अस्पताल में बेड की भारी कमी है, मरीज फर्श पर लेटे हैं।', language: 'hi', translatedText: 'There is a severe shortage of beds at the government hospital; patients are lying on the floor.', category: 'Healthcare', subCategory: 'Bed shortage', problem: 'Severe hospital bed shortage', location: { country: 'India', state: 'Bihar', district: 'Gaya' }, latitude: 24.8, longitude: 85.0, locationConfidence: 'HIGH', urgency: 'HIGH', confidence: 92, source: 'voice', timestamp: daysAgo(1) },
  { requestId: 'REQ-0018', originalText: 'गांव में पीने के साफ पानी की कोई व्यवस्था नहीं है।', language: 'hi', translatedText: 'There is no arrangement for clean drinking water in the village.', category: 'Water & Sanitation', subCategory: 'No clean water', problem: 'No access to clean drinking water', location: { country: 'India', state: 'Bihar', district: 'Gaya' }, latitude: 24.79, longitude: 84.98, locationConfidence: 'HIGH', urgency: 'HIGH', confidence: 90, source: 'text', timestamp: daysAgo(5) },
  { requestId: 'REQ-0019', originalText: 'Government hospital lacks basic diagnostic equipment for common illnesses.', language: 'en', translatedText: 'Government hospital lacks basic diagnostic equipment for common illnesses.', category: 'Healthcare', subCategory: 'Diagnostic equipment', problem: 'Missing basic diagnostic equipment', location: { country: 'India', state: 'Bihar', district: 'Gaya' }, latitude: 24.81, longitude: 85.01, locationConfidence: 'HIGH', urgency: 'HIGH', confidence: 87, source: 'text', timestamp: daysAgo(7) },
  { requestId: 'REQ-0020', originalText: 'हैंडपंप महीनों से खराब है, महिलाओं को दूर से पानी लाना पड़ता है।', language: 'hi', translatedText: 'The hand pump has been broken for months; women must fetch water from far away.', category: 'Water & Sanitation', subCategory: 'Broken hand pump', problem: 'Non-functional hand pump for months', location: { country: 'India', state: 'Bihar', district: 'Gaya' }, latitude: 24.77, longitude: 84.99, locationConfidence: 'MEDIUM', urgency: 'MEDIUM', confidence: 72, source: 'messaging', timestamp: daysAgo(19) },
  { requestId: 'REQ-0021', originalText: 'Village road becomes completely impassable during rains, cutting off access.', language: 'en', translatedText: 'Village road becomes completely impassable during rains, cutting off access.', category: 'Roads & Transport', subCategory: 'Seasonal access', problem: 'Village cut off during monsoon due to bad road', location: { country: 'India', state: 'Bihar', district: 'Gaya' }, latitude: 24.82, longitude: 85.03, locationConfidence: 'MEDIUM', urgency: 'MEDIUM', confidence: 75, source: 'text', timestamp: daysAgo(13) },
  { requestId: 'REQ-0022', originalText: 'गर्भवती महिलाओं के लिए नजदीक में कोई प्रसव सुविधा उपलब्ध नहीं है।', language: 'hi', translatedText: 'No nearby delivery facility is available for pregnant women.', category: 'Healthcare', subCategory: 'Maternal care', problem: 'No nearby maternal delivery facility', location: { country: 'India', state: 'Bihar', district: 'Gaya' }, latitude: 24.78, longitude: 85.02, locationConfidence: 'HIGH', urgency: 'HIGH', confidence: 93, source: 'voice', timestamp: daysAgo(2) },
  { requestId: 'REQ-0023', originalText: 'तालाब का पानी दूषित हो गया है, इससे बीमारियां फैल रही हैं।', language: 'hi', translatedText: 'The pond water has become contaminated, spreading illness.', category: 'Water & Sanitation', subCategory: 'Water contamination', problem: 'Contaminated water source causing illness', location: { country: 'India', state: 'Bihar', district: 'Gaya' }, latitude: 24.83, longitude: 84.97, locationConfidence: 'HIGH', urgency: 'HIGH', confidence: 91, source: 'text', timestamp: daysAgo(4) },

  // ---- Muzaffarpur (BR) ----
  { requestId: 'REQ-0024', originalText: 'बाढ़ के बाद से इलाके में पानी की निकासी नहीं हो रही है।', language: 'hi', translatedText: 'Water has not drained from the area since the flood.', category: 'Water & Sanitation', subCategory: 'Drainage', problem: 'Post-flood water stagnation and poor drainage', location: { country: 'India', state: 'Bihar', district: 'Muzaffarpur' }, latitude: 26.12, longitude: 85.39, locationConfidence: 'HIGH', urgency: 'HIGH', confidence: 86, source: 'voice', timestamp: daysAgo(3) },
  { requestId: 'REQ-0025', originalText: 'स्वास्थ्य केंद्र में सुबह जल्दी पहुंचने पर भी घंटों इंतजार करना पड़ता है।', language: 'hi', translatedText: 'Even arriving early morning, one has to wait hours at the health center.', category: 'Healthcare', subCategory: 'Wait times', problem: 'Excessive wait times at health center', location: { country: 'India', state: 'Bihar', district: 'Muzaffarpur' }, latitude: 26.1, longitude: 85.4, locationConfidence: 'MEDIUM', urgency: 'MEDIUM', confidence: 70, source: 'text', timestamp: daysAgo(16) },
  { requestId: 'REQ-0026', originalText: 'Voltage fluctuation is damaging household appliances frequently.', language: 'en', translatedText: 'Voltage fluctuation is damaging household appliances frequently.', category: 'Electricity', subCategory: 'Voltage fluctuation', problem: 'Frequent voltage fluctuation damaging appliances', location: { country: 'India', state: 'Bihar', district: 'Muzaffarpur' }, latitude: 26.13, longitude: 85.37, locationConfidence: 'MEDIUM', urgency: 'MEDIUM', confidence: 73, source: 'messaging', timestamp: daysAgo(10) },
  { requestId: 'REQ-0027', originalText: 'गांव के कुएं का पानी पीने योग्य नहीं रहा, कई लोग बीमार पड़े हैं।', language: 'hi', translatedText: 'The village well water is no longer drinkable; several people have fallen ill.', category: 'Water & Sanitation', subCategory: 'Water quality', problem: 'Undrinkable well water causing illness', location: { country: 'India', state: 'Bihar', district: 'Muzaffarpur' }, latitude: 26.11, longitude: 85.41, locationConfidence: 'HIGH', urgency: 'HIGH', confidence: 88, source: 'text', timestamp: daysAgo(5) },
  { requestId: 'REQ-0028', originalText: 'The pharmacy at the health center often runs out of common medicines.', language: 'en', translatedText: 'The pharmacy at the health center often runs out of common medicines.', category: 'Healthcare', subCategory: 'Medicine shortage', problem: 'Frequent medicine stockouts', location: { country: 'India', state: 'Bihar', district: 'Muzaffarpur' }, latitude: 26.09, longitude: 85.38, locationConfidence: 'MEDIUM', urgency: 'LOW', confidence: 62, source: 'text', timestamp: daysAgo(22) },

  // ---- Kolkata (WB) — good infra, low urgency ----
  { requestId: 'REQ-0029', originalText: 'ইন্টারনেট সংযোগ মাঝে মাঝে ধীর হয়ে যায়, বিশেষত সন্ধ্যার সময়।', language: 'bn', translatedText: 'Internet connectivity occasionally slows down, especially in the evening.', category: 'Internet & Digital Connectivity', subCategory: 'Bandwidth issue', problem: 'Evening internet slowdown', location: { country: 'India', state: 'West Bengal', district: 'Kolkata' }, latitude: 22.57, longitude: 88.36, locationConfidence: 'HIGH', urgency: 'LOW', confidence: 60, source: 'messaging', timestamp: daysAgo(33) },
  { requestId: 'REQ-0030', originalText: 'Classroom seating is a bit tight for the number of students enrolled.', language: 'en', translatedText: 'Classroom seating is a bit tight for the number of students enrolled.', category: 'Education', subCategory: 'Overcrowding', problem: 'Classroom overcrowding', location: { country: 'India', state: 'West Bengal', district: 'Kolkata' }, latitude: 22.58, longitude: 88.35, locationConfidence: 'MEDIUM', urgency: 'LOW', confidence: 57, source: 'text', timestamp: daysAgo(40) },
  { requestId: 'REQ-0031', originalText: 'রাস্তার একটি অংশে সামান্য খানাখন্দ আছে, খুব জরুরি নয়।', language: 'bn', translatedText: 'There is a minor pothole on part of the road, not very urgent.', category: 'Roads & Transport', subCategory: 'Minor road damage', problem: 'Minor pothole on side street', location: { country: 'India', state: 'West Bengal', district: 'Kolkata' }, latitude: 22.56, longitude: 88.37, locationConfidence: 'MEDIUM', urgency: 'LOW', confidence: 55, source: 'text', timestamp: daysAgo(45) },

  // ---- Siliguri (WB) ----
  { requestId: 'REQ-0032', originalText: 'পাহাড়ি রাস্তায় ধস নামার পর মেরামত হয়নি।', language: 'bn', translatedText: 'The hill road has not been repaired since a landslide.', category: 'Roads & Transport', subCategory: 'Landslide damage', problem: 'Unrepaired road after landslide', location: { country: 'India', state: 'West Bengal', district: 'Siliguri' }, latitude: 26.72, longitude: 88.39, locationConfidence: 'HIGH', urgency: 'MEDIUM', confidence: 79, source: 'voice', timestamp: daysAgo(12) },
  { requestId: 'REQ-0033', originalText: 'Local clinic needs more staff to handle the growing number of patients.', language: 'en', translatedText: 'Local clinic needs more staff to handle the growing number of patients.', category: 'Healthcare', subCategory: 'Staff shortage', problem: 'Clinic understaffed for patient volume', location: { country: 'India', state: 'West Bengal', district: 'Siliguri' }, latitude: 26.73, longitude: 88.4, locationConfidence: 'MEDIUM', urgency: 'MEDIUM', confidence: 71, source: 'text', timestamp: daysAgo(17) },
  { requestId: 'REQ-0034', originalText: 'গ্রামের এলাকায় মোবাইল নেটওয়ার্ক প্রায়ই থাকে না।', language: 'bn', translatedText: 'Mobile network is often unavailable in the rural areas.', category: 'Internet & Digital Connectivity', subCategory: 'No network coverage', problem: 'Poor mobile network coverage in rural pockets', location: { country: 'India', state: 'West Bengal', district: 'Siliguri' }, latitude: 26.71, longitude: 88.41, locationConfidence: 'MEDIUM', urgency: 'LOW', confidence: 64, source: 'messaging', timestamp: daysAgo(27) },
  { requestId: 'REQ-0035', originalText: 'বর্ষার সময় রাস্তায় জল জমে যাতায়াত কঠিন হয়ে পড়ে।', language: 'bn', translatedText: 'During monsoon, water accumulates on the road making travel difficult.', category: 'Roads & Transport', subCategory: 'Waterlogging', problem: 'Waterlogging on road during monsoon', location: { country: 'India', state: 'West Bengal', district: 'Siliguri' }, latitude: 26.74, longitude: 88.38, locationConfidence: 'MEDIUM', urgency: 'MEDIUM', confidence: 76, source: 'text', timestamp: daysAgo(9) },
  { requestId: 'REQ-0036', originalText: 'Vaccination camp visits are irregular in our neighborhood.', language: 'en', translatedText: 'Vaccination camp visits are irregular in our neighborhood.', category: 'Healthcare', subCategory: 'Immunization access', problem: 'Irregular vaccination camp schedule', location: { country: 'India', state: 'West Bengal', district: 'Siliguri' }, latitude: 26.7, longitude: 88.4, locationConfidence: 'MEDIUM', urgency: 'MEDIUM', confidence: 69, source: 'text', timestamp: daysAgo(21) },

  // ---- Purulia (WB) — weakest infra, high demand across sectors ----
  { requestId: 'REQ-0037', originalText: 'গ্রামে সরকারি জলের কল বহুদিন ধরে বন্ধ পড়ে আছে।', language: 'bn', translatedText: 'The government water tap in the village has been non-functional for a long time.', category: 'Water & Sanitation', subCategory: 'Broken water supply', problem: 'Long-broken government water tap', location: { country: 'India', state: 'West Bengal', district: 'Purulia' }, latitude: 23.33, longitude: 86.36, locationConfidence: 'HIGH', urgency: 'HIGH', confidence: 90, source: 'voice', timestamp: daysAgo(2) },
  { requestId: 'REQ-0038', originalText: 'নিকটবর্তী স্বাস্থ্যকেন্দ্রে কোনো ডাক্তার নিয়মিত আসেন না।', language: 'bn', translatedText: 'No doctor regularly visits the nearby health center.', category: 'Healthcare', subCategory: 'Doctor availability', problem: 'No regular doctor at nearby health center', location: { country: 'India', state: 'West Bengal', district: 'Purulia' }, latitude: 23.34, longitude: 86.35, locationConfidence: 'HIGH', urgency: 'HIGH', confidence: 92, source: 'text', timestamp: daysAgo(3) },
  { requestId: 'REQ-0039', originalText: 'গ্রামে বিদ্যুৎ সংযোগ এখনো পৌঁছায়নি, সন্ধ্যার পর সম্পূর্ণ অন্ধকার থাকে।', language: 'bn', translatedText: 'Electricity connection has still not reached the village; it is completely dark after evening.', category: 'Electricity', subCategory: 'No connection', problem: 'No electricity connection in village', location: { country: 'India', state: 'West Bengal', district: 'Purulia' }, latitude: 23.32, longitude: 86.37, locationConfidence: 'HIGH', urgency: 'HIGH', confidence: 89, source: 'voice', timestamp: daysAgo(6) },
  { requestId: 'REQ-0040', originalText: 'পুকুরের জলই একমাত্র জলের উৎস, যা প্রায়ই দূষিত থাকে।', language: 'bn', translatedText: 'Pond water is the only water source, and it is often contaminated.', category: 'Water & Sanitation', subCategory: 'Water contamination', problem: 'Only water source frequently contaminated', location: { country: 'India', state: 'West Bengal', district: 'Purulia' }, latitude: 23.31, longitude: 86.38, locationConfidence: 'HIGH', urgency: 'HIGH', confidence: 87, source: 'text', timestamp: daysAgo(4) },
  { requestId: 'REQ-0041', originalText: 'The nearest hospital with emergency care is over 30 km away from our village.', language: 'en', translatedText: 'The nearest hospital with emergency care is over 30 km away from our village.', category: 'Healthcare', subCategory: 'Facility distance', problem: 'Very long distance to emergency care', location: { country: 'India', state: 'West Bengal', district: 'Purulia' }, latitude: 23.335, longitude: 86.355, locationConfidence: 'HIGH', urgency: 'HIGH', confidence: 94, source: 'voice', timestamp: daysAgo(1) },
  { requestId: 'REQ-0042', originalText: 'বিদ্যুৎ থাকলেও তা অনিয়মিত এবং প্রায়ই কেটে যায়।', language: 'bn', translatedText: 'Even when electricity is present it is irregular and frequently cuts off.', category: 'Electricity', subCategory: 'Unreliable supply', problem: 'Irregular and unreliable electricity supply', location: { country: 'India', state: 'West Bengal', district: 'Purulia' }, latitude: 23.328, longitude: 86.362, locationConfidence: 'MEDIUM', urgency: 'MEDIUM', confidence: 75, source: 'messaging', timestamp: daysAgo(14) },
  { requestId: 'REQ-0043', originalText: 'নলকূপ থেকে জল আসা বন্ধ হয়ে গেছে দুই সপ্তাহ ধরে।', language: 'bn', translatedText: 'Water from the tubewell has stopped flowing for two weeks.', category: 'Water & Sanitation', subCategory: 'Broken tubewell', problem: 'Tubewell stopped functioning for two weeks', location: { country: 'India', state: 'West Bengal', district: 'Purulia' }, latitude: 23.336, longitude: 86.34, locationConfidence: 'MEDIUM', urgency: 'MEDIUM', confidence: 77, source: 'text', timestamp: daysAgo(10) },

  // ---- Bhubaneswar (OD) — strongest infra, low urgency ----
  { requestId: 'REQ-0044', originalText: 'Would be nice to have a few more computers in the school computer lab.', language: 'en', translatedText: 'Would be nice to have a few more computers in the school computer lab.', category: 'Education', subCategory: 'Equipment request', problem: 'Limited computers in school lab', location: { country: 'India', state: 'Odisha', district: 'Bhubaneswar' }, latitude: 20.3, longitude: 85.82, locationConfidence: 'MEDIUM', urgency: 'LOW', confidence: 55, source: 'text', timestamp: daysAgo(38) },
  { requestId: 'REQ-0045', originalText: 'Public Wi-Fi hotspot in the park sometimes disconnects, not a major issue.', language: 'en', translatedText: 'Public Wi-Fi hotspot in the park sometimes disconnects, not a major issue.', category: 'Internet & Digital Connectivity', subCategory: 'Connectivity glitch', problem: 'Occasional disconnection of public Wi-Fi', location: { country: 'India', state: 'Odisha', district: 'Bhubaneswar' }, latitude: 20.29, longitude: 85.83, locationConfidence: 'HIGH', urgency: 'LOW', confidence: 58, source: 'text', timestamp: daysAgo(42) },
  { requestId: 'REQ-0046', originalText: 'Streetlights in one lane take a while to get fixed when they go out.', language: 'en', translatedText: 'Streetlights in one lane take a while to get fixed when they go out.', category: 'Electricity', subCategory: 'Streetlight maintenance', problem: 'Slow streetlight repair turnaround', location: { country: 'India', state: 'Odisha', district: 'Bhubaneswar' }, latitude: 20.31, longitude: 85.81, locationConfidence: 'MEDIUM', urgency: 'LOW', confidence: 52, source: 'messaging', timestamp: daysAgo(50) },

  // ---- Cuttack (OD) ----
  { requestId: 'REQ-0047', originalText: 'Flyover construction has caused traffic congestion during peak hours.', language: 'en', translatedText: 'Flyover construction has caused traffic congestion during peak hours.', category: 'Roads & Transport', subCategory: 'Construction congestion', problem: 'Traffic congestion due to ongoing construction', location: { country: 'India', state: 'Odisha', district: 'Cuttack' }, latitude: 20.46, longitude: 85.88, locationConfidence: 'HIGH', urgency: 'MEDIUM', confidence: 74, source: 'text', timestamp: daysAgo(15) },
  { requestId: 'REQ-0048', originalText: 'Drainage near the market area overflows during heavy rain.', language: 'en', translatedText: 'Drainage near the market area overflows during heavy rain.', category: 'Water & Sanitation', subCategory: 'Drainage overflow', problem: 'Drainage overflow near market during rains', location: { country: 'India', state: 'Odisha', district: 'Cuttack' }, latitude: 20.47, longitude: 85.87, locationConfidence: 'MEDIUM', urgency: 'MEDIUM', confidence: 72, source: 'text', timestamp: daysAgo(11) },
  { requestId: 'REQ-0049', originalText: 'School requests additional teaching staff for science subjects.', language: 'en', translatedText: 'School requests additional teaching staff for science subjects.', category: 'Education', subCategory: 'Staff shortage', problem: 'Shortage of science teachers', location: { country: 'India', state: 'Odisha', district: 'Cuttack' }, latitude: 20.45, longitude: 85.89, locationConfidence: 'MEDIUM', urgency: 'LOW', confidence: 60, source: 'text', timestamp: daysAgo(24) },
  { requestId: 'REQ-0050', originalText: 'Some road signs on the bypass are missing or faded, causing confusion.', language: 'en', translatedText: 'Some road signs on the bypass are missing or faded, causing confusion.', category: 'Roads & Transport', subCategory: 'Signage', problem: 'Missing or faded road signage on bypass', location: { country: 'India', state: 'Odisha', district: 'Cuttack' }, latitude: 20.44, longitude: 85.9, locationConfidence: 'MEDIUM', urgency: 'MEDIUM', confidence: 70, source: 'text', timestamp: daysAgo(8) },
];

module.exports = citizenRequests;