// SYNTHETIC DEMO DATA ONLY — no real government statistics.
// Population values are fictional and calibrated only to produce
// clear analytical patterns for the CivicPulse demo.

const demographics = [
  {
    regionId: 'JH-RAN',
    country: 'India',
    stateProvince: 'Jharkhand',
    district: 'Ranchi',
    population: 2500000,
    populationDensity: 650,
    ruralPopulation: 1200000,
    urbanPopulation: 1300000,
    vulnerablePopulationIndicator: 55,
  },
  {
    regionId: 'JH-JSR',
    country: 'India',
    stateProvince: 'Jharkhand',
    district: 'Jamshedpur',
    population: 1500000,
    populationDensity: 850,
    ruralPopulation: 400000,
    urbanPopulation: 1100000,
    vulnerablePopulationIndicator: 30,
  },
  {
    regionId: 'JH-DHN',
    country: 'India',
    stateProvince: 'Jharkhand',
    district: 'Dhanbad',
    population: 2100000,
    populationDensity: 700,
    ruralPopulation: 900000,
    urbanPopulation: 1200000,
    vulnerablePopulationIndicator: 45,
  },
  {
    regionId: 'BR-GAY',
    country: 'India',
    stateProvince: 'Bihar',
    district: 'Gaya',
    population: 2400000,
    populationDensity: 500,
    ruralPopulation: 1900000,
    urbanPopulation: 500000,
    vulnerablePopulationIndicator: 65,
  },
  {
    regionId: 'BR-MUZ',
    country: 'India',
    stateProvince: 'Bihar',
    district: 'Muzaffarpur',
    population: 2200000,
    populationDensity: 480,
    ruralPopulation: 1800000,
    urbanPopulation: 400000,
    vulnerablePopulationIndicator: 60,
  },
  {
    regionId: 'WB-KOL',
    country: 'India',
    stateProvince: 'West Bengal',
    district: 'Kolkata',
    population: 4500000,
    populationDensity: 2400,
    ruralPopulation: 200000,
    urbanPopulation: 4300000,
    vulnerablePopulationIndicator: 25,
  },
  {
    regionId: 'WB-SIL',
    country: 'India',
    stateProvince: 'West Bengal',
    district: 'Siliguri',
    population: 700000,
    populationDensity: 400,
    ruralPopulation: 250000,
    urbanPopulation: 450000,
    vulnerablePopulationIndicator: 35,
  },
  {
    regionId: 'WB-PUR',
    country: 'India',
    stateProvince: 'West Bengal',
    district: 'Purulia',
    population: 1600000,
    populationDensity: 300,
    ruralPopulation: 1350000,
    urbanPopulation: 250000,
    vulnerablePopulationIndicator: 70,
  },
  {
    regionId: 'OD-BBS',
    country: 'India',
    stateProvince: 'Odisha',
    district: 'Bhubaneswar',
    population: 900000,
    populationDensity: 550,
    ruralPopulation: 150000,
    urbanPopulation: 750000,
    vulnerablePopulationIndicator: 20,
  },
  {
    regionId: 'OD-CTC',
    country: 'India',
    stateProvince: 'Odisha',
    district: 'Cuttack',
    population: 1100000,
    populationDensity: 600,
    ruralPopulation: 400000,
    urbanPopulation: 700000,
    vulnerablePopulationIndicator: 40,
  },
];

module.exports = demographics;